name: Build Mac Installer
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build DMG
        run: npm run pack:mac
      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: GFM-Engine-Mac
          path: dist/*.dmg
